services:
  app:
    build: .
    container_name: drop2print
    ports:
      - "8000:8000"
    volumes:
      - ./app/uploads:/app/app/uploads
      - ./app/db:/app/app/db
    environment: {}
    # Uncomment to force a specific printer for `lp`
    # environment:
    #   DROP2PRINT_PRINTER: my_printer
    restart: unless-stopped
